### PR TITLE
Kera routes

### PR DESCRIPTION
**Pull request by kera-cudmore**
Added the app.route for the 

• terms and conditions page
• privacy policy page
• 404 error page

• Updated the link to the privacy page in terms
• Updated the icons in the footer to be links

• updated external links so they follow the correct format for jinja - needed http:// at the beginning
• updated the terms link to the correct link from placeholder

### CODE REVIEW

**Comment by paulasdev** [comment]
Great job

**Comment by kera-cudmore** [comment]
@paulasdev - you'll need to merge these changes in rather than closing the issue, otherwise the changes aren't updated to the repo
 🙂

**Comment by paulasdev** [comment]
thanks Kera

**Review by paulasdev — COMMENTED** [review]
well done

**Review by andrewdempsey2018 — APPROVED** [review]
LGTM

**Pull request merged**
